"""Pydantic models for memory and context management in VQMS.

VQMS uses three memory tiers:
  - PostgreSQL persistent storage (long-term, queryable, includes cache tables)
  - pgvector semantic memory (embeddings for KB search)
  - In-graph agent state (LangGraph working memory)

These models define the data contracts for the PostgreSQL-backed
memory stores.

Corresponds to:
  - memory.episodic_memory table
  - memory.vendor_profile_cache table
  - memory.embedding_index table (pgvector)
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field

from src.models.vendor import VendorTier
from src.utils.helpers import ist_now


class EpisodicMemory(BaseModel):
    """A past query interaction stored for context enrichment.

    When agents process a new query, they load the vendor's
    episodic memories to understand past issues, resolution
    patterns, and preferences. Saved on case closure (Step 16).
    """

    memory_id: str = Field(description="UUID4 unique identifier")
    vendor_id: str = Field(description="Salesforce Account ID — indexed for lookup")
    query_id: str = Field(description="The query this memory relates to")
    summary: str = Field(
        description="Brief summary of the query and how it was resolved",
    )
    resolution_path: str | None = Field(
        default=None,
        description="Which path was taken: A, B, or C",
    )
    resolved_at: datetime | None = Field(
        default=None,
        description="When the query was resolved",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional context: category, urgency, satisfaction, etc.",
    )
    created_at: datetime = Field(default_factory=ist_now)


class VendorProfileCache(BaseModel):
    """Cached vendor profile from Salesforce.

    Stored in PostgreSQL cache table (cache.kv_store with 1-hour TTL).
    Prevents hitting Salesforce on every query for the same vendor.
    """

    vendor_id: str = Field(description="Salesforce Account ID")
    vendor_name: str = Field(description="Company name")
    vendor_tier: VendorTier = Field(
        default=VendorTier.STANDARD,
        description="SLA tier from Salesforce",
    )
    profile_data: dict[str, Any] = Field(
        default_factory=dict,
        description="Full profile: contact_email, account_manager, risk_flags, etc.",
    )
    cached_at: datetime = Field(default_factory=ist_now)
    ttl_seconds: int = Field(
        default=3600,
        description="Cache TTL in seconds (default 1 hour)",
    )


class EmbeddingRecord(BaseModel):
    """Vector embedding for a KB article chunk.

    Used by the KB Search Service (Step 9B) to find relevant
    knowledge base articles via cosine similarity search.
    Embeddings are generated by Amazon Bedrock Titan Embed v2
    with 1536 dimensions.
    """

    record_id: str = Field(description="UUID4 unique identifier")
    source_document: str = Field(
        description="KB article ID or filename this chunk came from",
    )
    chunk_text: str = Field(
        description="The text content of this chunk",
    )
    embedding: list[float] = Field(
        default_factory=list,
        description="Vector embedding (1536 dimensions for Titan Embed v2)",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Chunk metadata: category, chunk_index, document_id, etc.",
    )
    created_at: datetime = Field(default_factory=ist_now)
